name: Gang Loco
favicon: null
layout_spectrum: 0.5307618891820312
typography_spectrum: 0.659169675083831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8806750574149191
  lightness: 0.4993664249777794
  saturation: 0.6874193139374256
  rhythmicContrast: 0.11167978309094906
purpose: []
